import { mkdirSync, writeFileSync } from 'node:fs'
import * as path from 'node:path'

const domainNames = ['users', 'posts', 'comments', 'teams', 'projects'] as const
const routesPerDomain = 20
const simpleRoutesPerDomain = routesPerDomain - 4
const generatedDirectory = path.join(import.meta.dirname, '../generated')
const domainsDirectory = path.join(generatedDirectory, 'domains')

const appExportName = (domain: string) => `${domain}App`

const generateDomain = (domain: (typeof domainNames)[number]): string => {
  const simpleRoutes = Array.from({ length: simpleRoutesPerDomain }, (_, index) => {
    const item = index + 1
    return `
  .get('/items/${item}', (c) =>
    c.json(
      {
        domain: '${domain}' as const,
        item: ${item},
        requestId: c.get('requestId'),
      },
      200
    )
  )`
  }).join('')

  return `// Generated by scripts/generate-fixture.ts. Do not edit.
import { validator } from '../../../../src/validator/index.js'
import { factory, sharedMiddleware } from './shared.js'

export const ${appExportName(domain)} = factory
  .createApp()
  .use('*', sharedMiddleware)
  .get(
    '/representative/:id',
    validator('param', (value) => value as { id: string }),
    validator('query', (value) => value as { include: 'summary' | 'details' }),
    (c) => {
      const { id } = c.req.valid('param')
      const { include } = c.req.valid('query')
      if (id === 'missing') {
        return c.json({ error: '${domain} not found' as const }, 404)
      }
      return c.json(
        {
          domain: '${domain}' as const,
          id,
          include,
          requestId: c.get('requestId'),
        },
        200
      )
    }
  )
  .post(
    '/representative',
    validator('json', (value, c) => {
      if (!value || typeof value !== 'object' || !('name' in value)) {
        return c.json({ error: 'invalid ${domain} input' as const }, 400)
      }
      return value as { name: string }
    }),
    (c) => {
      const input = c.req.valid('json')
      return c.json({ domain: '${domain}' as const, id: '${domain}-created', name: input.name }, 201)
    }
  )
  .patch(
    '/representative/:id',
    validator('param', (value) => value as { id: string }),
    validator('json', (value) => value as { name: string }),
    (c) => {
      const { id } = c.req.valid('param')
      const { name } = c.req.valid('json')
      if (id === 'missing') {
        return c.json({ error: '${domain} not found' as const }, 404)
      }
      return c.json({ domain: '${domain}' as const, id, name }, 200)
    }
  )
  .delete(
    '/representative/:id',
    validator('param', (value) => value as { id: string }),
    (c) => {
      const { id } = c.req.valid('param')
      if (id === 'missing') {
        return c.json({ error: '${domain} not found' as const }, 404)
      }
      return c.json({ domain: '${domain}' as const, id, deleted: true as const }, 200)
    }
  )${simpleRoutes}
`
}

const shared = `// Generated by scripts/generate-fixture.ts. Do not edit.
import { createFactory } from '../../../../src/helper/factory/index.js'

export type BenchmarkEnv = {
  Variables: {
    requestId: string
  }
}

export const factory = createFactory<BenchmarkEnv>()
export const sharedMiddleware = factory.createMiddleware(async (c, next) => {
  c.set('requestId', 'benchmark-request')
  await next()
})
`

const domainIndex = `// Generated by scripts/generate-fixture.ts. Do not edit.
export { factory } from './shared.js'
${domainNames
  .map((domain) => `export { ${appExportName(domain)} } from './${domain}.js'`)
  .join('\n')}
`

const parent = `// Generated by scripts/generate-fixture.ts. Do not edit.
import type { ExtractSchema } from '../../../src/types.js'
import { commentsApp, factory, postsApp, projectsApp, teamsApp, usersApp } from './domains/index.js'

export const app = factory
  .createApp()
  .route('/users', usersApp)
  .route('/posts', postsApp)
  .route('/comments', commentsApp)
  .route('/teams', teamsApp)
  .route('/projects', projectsApp)

export type ParentSchema = ExtractSchema<typeof app>
export type ParentRepresentative = ParentSchema['/users/representative/:id']['$get']
`

mkdirSync(domainsDirectory, { recursive: true })
writeFileSync(path.join(domainsDirectory, 'shared.ts'), shared)
for (const domain of domainNames) {
  writeFileSync(path.join(domainsDirectory, `${domain}.ts`), generateDomain(domain))
}
writeFileSync(path.join(domainsDirectory, 'index.ts'), domainIndex)
writeFileSync(path.join(generatedDirectory, 'parent.ts'), parent)
process.stderr.write(
  `Generated ${domainNames.length} domain modules with ${routesPerDomain} routes each and one parent composition.\n`
)
