/**
 * @module
 * This module enables JSX to supports streaming Response.
 */

import { raw } from '../helper/html'
import { HtmlEscapedCallbackPhase, resolveCallback } from '../utils/html'
import type { HtmlEscapedString } from '../utils/html'
import { isUntrustedObject, renderChildren, renderUntrustedObject } from './base'
import type { JSXNode } from './base'
import { childrenToString } from './components'
import { DOM_RENDERER, DOM_STASH } from './constants'
import { captureRenderContext, createContext, useContext } from './context'
import { Suspense as SuspenseDomRenderer } from './dom/components'
import { buildDataStack } from './dom/render'
import type { HasRenderToDom, NodeObject } from './dom/render'
import { renderToChunks, StreamingRenderModeContext } from './streaming-internal'
import type { Child, FC, PropsWithChildren, Context as JSXContext } from './'

/**
 * Used to specify nonce for scripts generated by `Suspense` and `ErrorBoundary`.
 *
 * @example
 * ```tsx
 * <StreamingContext.Provider value={{ scriptNonce: 'test-nonce' }}>
 *   <Suspense fallback={<p>Loading...</p>}>
 *     <Content />
 *   </Suspense>
 * </StreamingContext.Provider>
 * ```
 */
export const StreamingContext: JSXContext<{ scriptNonce: string } | null> = createContext<{
  scriptNonce: string
} | null>(null)

let suspenseCounter = 0

const serializeBoundaryChild = (child: Child): string | Promise<string> =>
  typeof child === 'string' || Array.isArray(child)
    ? renderChildren([child])
    : child == null || typeof child === 'boolean'
      ? ''
      : isUntrustedObject(child)
        ? renderUntrustedObject(child)
        : child.toString()

/**
 * @experimental
 * `Suspense` is an experimental feature.
 * The API might be changed.
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const Suspense: FC<PropsWithChildren<{ fallback: any }>> = async ({
  children,
  fallback,
}) => {
  if (!Array.isArray(children)) {
    children = [children]
  }

  const nonce = useContext(StreamingContext)?.scriptNonce
  const renderMode = useContext(StreamingRenderModeContext)

  let resArray: HtmlEscapedString[] | Promise<HtmlEscapedString[]>[] = []

  // for use() hook
  const stackNode = { [DOM_STASH]: [0, []] } as unknown as NodeObject
  const popNodeStack = () => {
    buildDataStack.pop()
  }

  try {
    stackNode[DOM_STASH][0] = 0
    buildDataStack.push([[], stackNode])
    resArray = children.map(serializeBoundaryChild) as HtmlEscapedString[]
  } catch (e) {
    if (e instanceof Promise) {
      // Capture before deferring: on the fallback path the render context is
      // observable here but not in the `.then()` below.
      const resume = captureRenderContext()
      resArray = [
        e.then(() =>
          resume(() => {
            stackNode[DOM_STASH][0] = 0
            buildDataStack.push([[], stackNode])
            return childrenToString(children as Child[]).finally(popNodeStack)
          })
        ),
      ] as Promise<HtmlEscapedString[]>[]
    } else {
      throw e
    }
  } finally {
    popNodeStack()
  }

  if (resArray.some((res) => (res as {}) instanceof Promise)) {
    const index = suspenseCounter++
    const fallbackStr = await (typeof fallback === 'string' || Array.isArray(fallback)
      ? renderChildren([fallback])
      : isUntrustedObject(fallback)
        ? renderUntrustedObject(fallback)
        : fallback.toString())
    return raw(`<template id="H:${index}"></template>${fallbackStr}<!--/$-->`, [
      ...(fallbackStr.callbacks || []),
      ({ phase, buffer, context }) => {
        if (phase === HtmlEscapedCallbackPhase.BeforeStream) {
          return
        }
        return Promise.all(resArray).then(async (htmlArray) => {
          htmlArray = htmlArray.flat()
          const content = htmlArray.join('')
          if (buffer) {
            buffer[0] = buffer[0].replace(
              new RegExp(`<template id="H:${index}"></template>.*?<!--/\\$-->`),
              () => content
            )
          }
          const replacementScript =
            renderMode === 'partial'
              ? ''
              : `<script${nonce ? ` nonce="${nonce}"` : ''}>
((d,c,n) => {
c=d.currentScript.previousSibling
d=d.getElementById('H:${index}')
if(!d)return
do{n=d.nextSibling;n.remove()}while(n.nodeType!=8||n.nodeValue!='/$')
d.replaceWith(c.content)
})(document)
</script>`
          let html = buffer
            ? ''
            : `<template data-hono-target="H:${index}">${content}</template>${replacementScript}`

          const callbacks = htmlArray
            .map((html) => (html as HtmlEscapedString).callbacks || [])
            .flat()
          if (!callbacks.length) {
            return html
          }

          if (phase === HtmlEscapedCallbackPhase.Stream) {
            html = await resolveCallback(html, HtmlEscapedCallbackPhase.BeforeStream, true, context)
          }

          return raw(html, callbacks)
        })
      },
    ])
  } else {
    return raw(resArray.join(''))
  }
}
;(Suspense as HasRenderToDom)[DOM_RENDERER] = SuspenseDomRenderer

const textEncoder = new TextEncoder()

/**
 * @experimental
 * `renderToReadableStream()` is an experimental feature.
 * The API might be changed.
 */
export const renderToReadableStream = (
  content: HtmlEscapedString | JSXNode | Promise<HtmlEscapedString>,
  onError: (e: unknown) => string | void = console.trace
): ReadableStream<Uint8Array> => {
  let cancelled = false
  const reader = new ReadableStream<Uint8Array>({
    async start(controller) {
      try {
        for await (const chunk of renderToChunks(content, onError)) {
          if (!cancelled) {
            controller.enqueue(textEncoder.encode(chunk))
          }
        }
      } catch (e) {
        onError(e)
      }

      if (!cancelled) {
        controller.close()
      }
    },
    cancel() {
      cancelled = true
    },
  })
  return reader
}
